#!/usr/bin/env python3
"""Build Site Script - Generates static HTML from markdown summaries.

This script is run by GitHub Actions to build the static website
from the markdown summary files.
"""

import os
import re
import json
import yaml
import logging
from datetime import datetime
from typing import Dict, List, Optional
from pathlib import Path
from jinja2 import Environment, select_autoescape, Template

# Setup logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Paths
BASE_DIR = Path(__file__).parent.parent
SUMMARIES_DIR = BASE_DIR / 'summaries'
DOCS_DIR = BASE_DIR / 'docs'
CONFIG_DIR = BASE_DIR / 'config'

# Templates
INDEX_TEMPLATE = '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RSS AI Digest - AI-Powered Article Summaries</title>
    <link rel="stylesheet" href="assets/style.css">
    <link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>🤖</text></svg>">
    <meta name="description" content="AI-powered article summaries from RSS feeds">
</head>
<body>
    <header>
        <div class="container">
            <div class="logo">🤖</div>
            <h1><a href=".">RSS AI Digest</a></h1>
            <p class="subtitle">AI-powered article summaries from RSS feeds</p>
            <div class="stats">
                <span class="stat-item">{{ articles|length }} articles</span>
                <span class="stat-divider">•</span>
                <span class="stat-item">{{ sources|length }} sources</span>
            </div>
        </div>
    </header>

    <main class="container">
        <div class="filters">
            <div class="filter-group">
                <label for="source-filter">
                    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                        <polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3"></polygon>
                    </svg>
                    Filter by source:
                </label>
                <select id="source-filter">
                    <option value="all">All Sources</option>
                    {% for source in sources %}
                    <option value="{{ source }}">{{ source }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="search-group">
                <label for="search-input">
                    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                        <circle cx="11" cy="11" r="8"></circle>
                        <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
                    </svg>
                    Search:
                </label>
                <input type="text" id="search-input" placeholder="Search articles...">
            </div>
        </div>

        <div class="articles-list" id="articles-list">
            {% for date, date_articles in articles_by_date.items() %}
            <section class="date-group">
                <h2 class="date-header">
                    <span class="date-icon">📅</span>
                    {{ date }}
                    <span class="article-count">{{ date_articles|length }}</span>
                </h2>
                {% for article in date_articles %}
                <article class="article-card" data-source="{{ article.source }}">
                    <div class="card-header">
                        <h3>
                            <a href="{{ article.url }}" target="_blank">
                                {{ article.title }}
                            </a>
                        </h3>
                        <span class="source-tag">{{ article.source }}</span>
                    </div>
                    <div class="summary-full">
                        {{ article.content | safe }}
                    </div>
                </article>
                {% endfor %}
            </section>
            {% endfor %}
        </div>
    </main>

    <footer>
        <div class="container">
            <p>Generated by RSS AI Digest</p>
            <p class="footer-note">Powered by AI • Updated daily</p>
        </div>
    </footer>

    <script src="assets/filter.js"></script>
</body>
</html>'''

ARTICLE_TEMPLATE = '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ article.title }} - RSS AI Digest</title>
    <link rel="stylesheet" href="../assets/style.css">
    <link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>🤖</text></svg>">
    <meta name="description" content="{{ article.content[:200] }}...">
</head>
<body>
    <header>
        <div class="container">
            <div class="logo">🤖</div>
            <h1><a href="../">RSS AI Digest</a></h1>
            <p class="subtitle">AI-powered article summaries</p>
        </div>
    </header>

    <main class="container">
        <article class="article-detail">
            <header class="article-header">
                <h1>{{ article.title }}</h1>
                <div class="meta">
                    <span class="source">{{ article.source }}</span>
                    <span class="date">{{ article.published }}</span>
                </div>
                <a href="{{ article.url }}" target="_blank" class="original-link">Read Original Article →</a>
            </header>

            <div class="article-content">
                {{ article.content | safe }}
            </div>

            <div class="article-footer">
                <div class="ai-info">
                    <span class="ai-badge">AI Summary</span>
                    <span class="ai-provider">Generated by {{ article.ai_provider }}</span>
                </div>
            </div>
        </article>

        <a href="../" class="back-link">← Back to all articles</a>
    </main>

    <footer>
        <div class="container">
            <p>Generated by RSS AI Digest</p>
            <p class="footer-note">Powered by AI • Updated daily</p>
        </div>
    </footer>
</body>
</html>'''


def format_content(content: str) -> str:
    """Format content by splitting into paragraphs based on 【 markers."""
    # Split by 【 which marks different sections
    sections = re.split(r'(【[^】]+】)', content)

    formatted_parts = []
    for section in sections:
        if section.startswith('【'):
            # This is a section header, wrap it in strong tag
            formatted_parts.append(f'<strong>{section}</strong>')
        elif section.strip():
            # This is content, wrap in p tag
            formatted_parts.append(f'<p>{section.strip()}</p>')

    return '\n'.join(formatted_parts)


def parse_article_metadata(markdown: str) -> Dict:
    """Parse YAML frontmatter from markdown."""
    metadata = {}

    # Extract frontmatter
    if markdown.startswith('---'):
        parts = markdown.split('---', 2)
        if len(parts) >= 3:
            frontmatter = parts[1]
            content = parts[2].strip()

            # Parse YAML
            try:
                metadata = yaml.safe_load(frontmatter) or {}
            except yaml.YAMLError:
                logger.warning("Failed to parse frontmatter")

            metadata['content'] = content

    return metadata


def load_all_articles() -> List[Dict]:
    """Load all articles from summaries directory."""
    articles = []

    if not SUMMARIES_DIR.exists():
        logger.warning(f"Summaries directory not found: {SUMMARIES_DIR}")
        return articles

    # Walk through all markdown files
    for md_file in SUMMARIES_DIR.rglob('*.md'):
        try:
            with open(md_file, 'r', encoding='utf-8') as f:
                content = f.read()

            metadata = parse_article_metadata(content)

            # Extract date from path
            parts = md_file.parts
            if 'summaries' in parts:
                idx = parts.index('summaries')
                if idx + 3 <= len(parts) - 1:
                    year = parts[idx + 1]
                    month = parts[idx + 2]
                    day = parts[idx + 3].replace('.md', '')
                    date = f"{year}-{month}-{day}"
                else:
                    date = datetime.now().strftime('%Y-%m-%d')
            else:
                date = metadata.get('published', datetime.now().strftime('%Y-%m-%d'))

            filename = os.path.basename(str(md_file)).replace('.md', '.html')

            article = {
                'title': metadata.get('title', 'Untitled'),
                'source': metadata.get('source', 'Unknown'),
                'url': metadata.get('url', ''),
                'published': date,
                'summarized': metadata.get('summarized', ''),
                'ai_provider': metadata.get('ai_provider', 'unknown'),
                'content': metadata.get('content', ''),
                'filename': filename,
            }

            articles.append(article)

        except Exception as e:
            logger.error(f"Error reading {md_file}: {e}")
            continue

    # Sort by date descending
    articles.sort(key=lambda x: x['published'], reverse=True)

    return articles


def group_articles_by_date(articles: List[Dict]) -> Dict[str, List[Dict]]:
    """Group articles by date."""
    groups = {}
    for article in articles:
        date = article['published']
        if date not in groups:
            groups[date] = []
        groups[date].append(article)
    return groups


def get_all_sources(articles: List[Dict]) -> List[str]:
    """Get all unique sources from articles."""
    sources = set()
    for article in articles:
        sources.add(article['source'])
    return sorted(list(sources))


def build_site():
    """Build the static site."""
    logger.info("Building static site...")

    # Ensure docs directory exists
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    (DOCS_DIR / 'assets').mkdir(parents=True, exist_ok=True)

    # Load articles
    articles = load_all_articles()
    logger.info(f"Loaded {len(articles)} articles")

    if not articles:
        logger.warning("No articles found, creating empty site")
        # Create a simple placeholder index
        with open(DOCS_DIR / 'index.html', 'w', encoding='utf-8') as f:
            f.write("<html><body><h1>No articles yet</h1></body></html>")
        return

    # Get unique sources
    sources = get_all_sources(articles)

    # Generate index.html
    articles_by_date = group_articles_by_date(articles)

    # Create a custom filter for basename
    def _basename(path):
        return os.path.basename(path)

    env = Environment(autoescape=select_autoescape(['html', 'xml']))
    env.filters['basename'] = _basename

    try:
        index_template = env.from_string(INDEX_TEMPLATE)
        index_html = index_template.render(
            articles=articles,
            articles_by_date=articles_by_date,
            sources=sources
        )

        with open(DOCS_DIR / 'index.html', 'w', encoding='utf-8') as f:
            f.write(index_html)

        logger.info(f"Generated {DOCS_DIR / 'index.html'}")
    except Exception as e:
        logger.error(f"Error generating index: {e}")
        raise

    # Generate individual article pages
    article_template = env.from_string(ARTICLE_TEMPLATE)

    for article in articles:
        try:
            # Create date-based directory
            date_dir = DOCS_DIR / article['published']
            date_dir.mkdir(parents=True, exist_ok=True)

            # Generate filename
            filename = article['filename']

            # Format content with proper paragraph breaks
            article['content'] = format_content(article['content'])

            html = article_template.render(article=article)

            with open(date_dir / filename, 'w', encoding='utf-8') as f:
                f.write(html)

        except Exception as e:
            logger.error(f"Error generating article page for {article['title']}: {e}")
            continue

    logger.info("Site build complete!")


if __name__ == '__main__':
    build_site()